### ISSUE TITLE
Backend PoC Coding

### ISSUE THREAD

**Issue by LukasMeister** [amosproj/amos-ss2021-bike-nest#59]
Prototype a solution (proof of concept) to show different bike nests.

**Comment by richmandlx** [comment]
A basic setup is finished.
I created to Spring Projects inside the Backend Folder. 
Those projects contain a dockerfile with instructions on how to build the container. For the container building the jar from build/libs/ is taken.
This means that the workflow should be like this: 
- Code in the respective service project
- Build the project so that the jar gets updated
- inside the backend folder run "docker-compose build <service>" with the name of the service that you edited. so far you can use "bikenest" or "booking" for that
- to start up everything you should run "docker-compose up" afterwards or "docker-compose -f docker-compose-debug.yml up"
The bikenest service will be available under localhost:9001
booking service under localhost:9002

**Comment by richmandlx** [comment]
Now this PoC should be ready for the wished usecase (getting bikenest locations from the backend).
I added the API Gateway.

What's still missing is an authentication mechanism.
