### ISSUE TITLE
Better Error Handling for Booking Service

### ISSUE THREAD

**Issue by JodelLisa2Point0** [amosproj/amos-ss2021-bike-nest#92]

**Comment by richmandlx** [comment]
During Frontend Testing we noticed, that the Booking Service doesn't really validate the Input it gets. For example if no BikenestId is set in a request to /booking/add then an exception happens inside the service. Therefore the result to the frontend is an internal server error instead of a meaningful error message.
An example how we could fix this, is already done in usermgmt service with the Valid Annotations.

**Comment by richmandlx** [comment]
Fixed d0dddae
