### ISSUE TITLE
Create account / login: refactor response message (currently error-prone)

### ISSUE THREAD

**Issue by LukasMeister** [amosproj/amos-ss2021-bike-nest#94]

**Comment by richmandlx** [comment]
Im still not too sure, how exactly we should do this.
The Backend has the knowledge about what went wrong.
For create account / login, we should definitely tell the user, what the error was.
Currently the Backend returns success=true or success=false and in the false case, there is an english error message.
Should we just return a german message that can be displayed to the user?
Or return status codes, that will be transformed into messages by a class in the frontend?
For that we would always have to synchronize the code base between frontend and backend though (if backend adds a new status code, than we would have to edit the frontend class, so that it can correctly transform the status code into a german message)

**Comment by richmandlx** [comment]
A solution might be, to define all error codes in the backend and provide an API Endpoint, that will return a german (or english) dictionary that contains all the status code mappings like this:
```
{
  "1000": "Username does not exist.",
  "1001": "Password is incorrect."
}
```

```
{
  "1000": "Der Nutzername existiert nicht.",
  "1001": "Das Passwort ist falsch."
}
```
